import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/primitives';
import Provider from '@/components/primitives/Provider';
import { Workflow } from '@/components/ui/Breadcrumbs';
import { auth } from '@/lib/auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Book Reselling App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await auth();

	return (
		<html lang="en">
			<body className={inter.className}>
				<Provider>
					<main className="min-h-screen flex flex-col ">
						<Header user={session?.user} />
						<Workflow />
						{children}
					</main>
				</Provider>
			</body>
		</html>
	);
}
