import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/primitives';
import Provider from '@/components/primitives/Provider';
import { Workflow } from '@/components/ui/Breadcrumbs';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Book Reselling App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<Provider>
				<body className={inter.className}>
					<main className="min-h-screen flex flex-col ">
						{/* <Header /> */}
						<Workflow />
						{children}
					</main>
				</body>
			</Provider>
		</html>
	);
}
